# Base de Datos con postgres

server:
    port: 8080
    tomcat: 
        accesslog:
            enabled: true
spring:
    application:
        name: lucas-backend
    datasource:
        url: jdbc:sqlserver://localhost:1433;database=bank;encrypt=true;trustServerCertificate=true;
        username: sa
        password: 1234Banco
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                format-sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non-contextual-creation: true

# Flyway

    flyway:
        baseline-version: 1
        encoding: UTF-8
        enabled: true  
        baseline-on-migrate: true  
        locations: classpath:db/migration  
        schemas: public  
        out-of-order: true
        validate-on-migrate: true