#spring.datasource.url=jdbc:postgresql://dpg-cjhshp5mrchc73asugh0-a.frankfurt-postgres.render.com/bankms
#spring.datasource.username=bankms_user
#spring.datasource.password=HL3l7cd9fmAVsPYhUzO9hq0jUjxuOg7R

server:
    tomcat:
        accesslog:
            enabled: true

spring:
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher
    application:
        name: bank-management-system
    port: 8002
    datasource:
        url: jdbc:postgresql://localhost:5432/bank-management-system
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        hibernate:
            ddl-auto: update



# Flyway

    flyway:
        baseline-version: 1
        encoding: UTF-8
        enabled: true  
        baseline-on-migrate: true  
        locations: classpath:db/migration  
        schemas: public  
        out-of-order: true
        validate-on-migrate: true
