server:
  tomcat:
    accesslog:
      enabled: true

spring:
  mvc:
    path match:
      matching-strategy: ant-path-matcher
  application:
    name: imagin_java_version
  port: 8080
  datasource:
    url: jdbc:postgresql://localhost:5432/imagin_java_version
    username: postgres
    password: sasa
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        id:
          new-generator-mappings: false
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non-contextual-creation: true
    hibernate:
      ddl-auto: validate




  # Flyway

  flyway:
    baseline-version: 1
    encoding: UTF-8
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    out-of-order: true
    validate-on-migrate: true
